service:
  name: 'Registration Auth Service'
  # external url of my own "dropoff" endpoint. This must match the OAuth2 redirect_url setting on each client
  dropoff_endpoint_url: https://my.own.domain.example.com/v1/dropoff
server:
  port: 4712
security:
  oidc:
    # used for parsing the id token cookie (userinfo endpoint only), not used for creating the cookie
    id_token_cookie_name: 'JWT'
    # used for creating and parsing the access token cookie (used by userinfo endpoint only)
    access_token_cookie_name: 'AUTH'
    # roles to pass through in the userinfo endpoint (all others are filtered)
    relevant_groups:
      - admin
    # optional, allows local validation of tokens before they are even sent to the user info endpoint. Not good for production performance if omitted.
    token_public_keys_PEM:
      - |
        -----BEGIN PUBLIC KEY-----
        MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAu1SU1LfVLPHCozMxH2Mo
        4lgOEePzNm0tRgeLezV6ffAt0gunVTLw7onLRnrq0/IzW7yWR7QkrmBL7jTKEn5u
        +qKhbwKfBstIs+bMY2Zkp18gnTxKLxoS2tFczGkPLPgizskuemMghRniWaoLcyeh
        kd3qqGElvW/VDL5AaWTg0nLVkjRo9z+40RQzuVaE8AkAFmxZzow3x+VJYKdjykkJ
        0iT9wCS0DRTXu269V264Vf/3jvredZiKRkgwlL9xNAwxXFg0x/XFw005UWVRIkdg
        cKWTjpBP2dPwVZ4WWC+9aGVd+Gyn1o0CLelf4rEjGoXbAAEgAqeGUxrcIlbjXfbc
        mwIDAQAB
        -----END PUBLIC KEY-----
    # optional, if not configured, local validation is used if the key is provided. Not safe for production if omitted.
    user_info_url: 'https://my.identity.provider.example.com/user-info'
    user_info_cache_seconds: 10
    audience: 'only-allowed-audience-in-tokens'
    issuer: 'only-allowed-issuer-in-tokens'
  cors:
    # set this to true to send disable cors headers - not for production - local/test instances only - will log lots of warnings
    disable: false
    # if setting disable_cors, you should also specify this, as a comma separated list of allowed origins
    allow_origin: 'http://localhost:8000'
    # set this to true to disable the secure cookie flag (useful for proxies on localhost only) - not for production - will log lots of warnings
    insecure_cookies: false
    # set this to true to disable the http only flag (useful for debugging purposes) - not for production - will log lots of warnings
    disable_http_only_cookies: false
logging:
  severity: INFO
identity_provider:
  authorization_endpoint: https://my.identity.provider.example.com/auth
  token_endpoint: https://my.identity.provider.example.com/token
  end_session_endpoint: https://my.identity.provider.example.com/logout
  token_request_timeout: 5s
  auth_request_timeout: 600s
application_configs:
  example-service:
    display_name: Example Service
    scope: 'example openid email groups profile'
    client_id: IAmNotSoSecret.
    client_secret: IAmVerySecret!
    default_dropoff_url: https://example.com/app/
    dropoff_url_pattern: https://example.com/app/(\?(foo=[a-z]+|bar=[0-9]{3,8}|&)+)?
    # note that the userinfo endpoint only works for those applications where this matches security.oidc.id_token_cookie_name
    # we do support multiple application configs, but for now, you only get userinfo for one of them
    cookie_name: JWT
    cookie_domain: example.com
    cookie_path: /app
    cookie_expiry: 6h
