name: Create and publish Docker image

on:
  push:
    branches:
      - 'issue-53-docker-build'

# a comment we can change again

jobs:
  call_build-and-push-image:
    permissions:
      contents: read
      packages: write
    uses: eurofurence/reg-workflows/.github/workflows/docker-build-push.yml@1-add-docker-build-workflow
    with:
      image-name: ${{ github.repository }}
      image-tags: latest
      full-repo-url: https://github.com/${{ github.repository }}
      branch-or-tag-name: ${{ github.ref_name }}
      commit-hash: ${{ github.sha }}
      registry-user: ${{ github.actor }}
    secrets:
      registry-pass: ${{ secrets.GITHUB_TOKEN }}
